[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#676965"
blue = "#83afd8"
cyan = "#37e5e7"
green = "#98e342"
magenta = "#bc93b6"
red = "#f44135"
white = "#f1f1ef"
yellow = "#fcea60"

[colors.cursor]
cursor = "#f44135"
text = "#ffffff"

[colors.normal]
black = "#000000"
blue = "#0f4072"
cyan = "#00a7aa"
green = "#5da602"
magenta = "#88658d"
red = "#d71e00"
white = "#dbded8"
yellow = "#cfad00"

[colors.primary]
background = "#2a2a2a"
foreground = "#dedede"

[colors.selection]
background = "#c1ddff"
text = "#000000"

[font]
size = 15.5

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.bold_italic]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[font.normal]
family = "FiraCode Nerd Font Mono"
style = "Medium"

[[keyboard.bindings]]
key = "NumpadEnter"
chars = "\n"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "exit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013d"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013p"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013n"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0013q"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0013%"
key = "Right"
mods = "Control|Command|Shift"

[[keyboard.bindings]]
chars = "\u0013h"
key = "Left"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0013j"
key = "Up"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0013k"
key = "Down"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0013l"
key = "Right"
mods = "Control|Command"

[[keyboard.bindings]]
chars = "\u0013\""
key = "Down"
mods = "Control|Command|Shift"

[[keyboard.bindings]]
chars = "\u0013e"
key = "Right"
mods = "Command|Shift"

[selection]
save_to_clipboard = true

[window]
opacity = 0.85

[[hints.enabled]]
command = "open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
mouse.mods = "Command"
#binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"
